### ISSUE TITLE
Plone 5.0.4 import error while starting

### ISSUE THREAD

**Issue by techsup** [collective/collective.lineage#44] opened 2016-05-03 01:05 UTC
Plone 5.0.4 with collective.lineage 2.0 crashes with import error on start:
...
ConfigurationError: ('Invalid value for', 'provides', 'ImportError: Module plone.app.imaging.interfaces has no global IImagingSchema')

**Comment by thet** [comment] 2016-05-03 07:35
Duplicate of https://github.com/collective/collective.lineage/issues/38

**Closed by thet** 2016-05-03 07:35 UTC
